services:
  client:
    build: ./client
    ports:
      - "3050:3050"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      MONGO_URL: 'mongodb+srv://holliemwangi:H0llies@m@tmcluster.zbhbjtc.mongodb.ne/'

  mongo:
    image: mongo:4.4
    ports:
      - "3000:3000"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
