---
- name: Dockerize and Run YOLO E-Commerce App
  hosts: all
  become: true

  # Including variables from an external file for better manageability
  vars_files: 
    - roles/frontend-deployment/vars/vars.yml

  # Defining the roles to structure the playbook
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    