---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  vars_files : roles/frontend-deployment/vars/vars.yml
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    