---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes


- name: Log in to Docker Hub
  docker_loginu:
    username: "holidahmwangi23"
    password: "+e!3tyqN4&EcH4T"

- name: Pull frontend image from Docker Hub
  docker_image:
    name: holidahmwangi23/yoloproject:V1.0.3
    source: pull

- name: Create Docker network
  docker_network:
    name: yolo_default

- name: Create React Frontend Container
  docker_container:
    name: yolo_frontend
    image: holidahmwangi23/yoloproject:V1.0.3
    networks:
      - name: yolo_default
    ports:
      - "3000:3000"
    command: "npm start"
    update_cache: yes
    become: yes
  

