---

- name: Clone frontend repository
  git:
    repo: 'https://github.com/yourusername/yolo-frontend.git'
    dest: /home/holidah/Downloads/DevopsClass/Dev06/yolo/client


- name: Pull image from repository
  docker_image:
    name: holidahmwangi23/yoloproject:V1.0.3
    source: pull

- name: Create Node.js Frontend Container
  docker_container:
    name: vibrant_curie
    image: yolo-client:V1.0.3
    networks:
      - yolo_default
      - name: yolo_app
    ports:
      - "3000:3000"
    command: "npm start"
  become: yes