# ---
# - name: Pull image from repository
#   docker_image:
#     name: holidahmwangi23/yoloprojectbackend:V1.0.1
#     source: pull



# - name: Create Node.js Backend Container
#   docker_container:
#     name: elegant_dijkstra
#     image: yolo-backend:V1.0.1
#     networks:
#       - yolo_default
#       - name: yolo_app
#     ports:
#       - "5000:5000"
#     command: "npm start"
#   become: yes

  

---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Log in to Docker Hub
  docker_login:
    username: "holidahmwangi23"
    password: "+e!3tyqN4&EcH4T"

- name: Pull backend image from Docker Hub
  docker_image:
    name: holidahmwangi23/yoloprojectbackend:V1.0.1
    source: pull

- name: Create Docker network
  docker_network:
    name: yolo_default

- name: Create Node.js Backend Container
  docker_container:
    name: yolo_backend
    image: holidahmwangi23/yoloprojectbackend:V1.0.1
    networks:
      - name: yolo_default
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes
