---
- name: Pull image from repository
  docker_image:
    name: holidahmwangi23/yoloprojectbackend:V1.0.1
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: elegant_dijkstra
    image: yolo-backend:V1.0.1
    networks:
      - yolo_default
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes